export var secretaryData = [
  {
    department: "BAŞKANLIK",
    units: [
      {
        id: 11047,
        department: "BAŞKANLIK",
        unit: "ÖZEL KALEM MÜDÜRLÜĞÜ",
        total_count: 2,
        amount: 628,
        total: 10.24,
        ANKARA_NİĞDE_OTOYOLU: 0,
        AVRASYA_TÜNELİ: 0,
        GEBZE_ORHANGAZİ_İZMİR_OTOYOLU: 0,
        İSTANBUL_DENİZ_OTOBÜSLERİ_İDO: 0,
        KARAYOLLARI_GENEL_MÜDÜRLÜĞÜ: 10.24,
        KUZEY_ÇEVRE_OTOYOLU: 0,
        KUZEY_EGE_OTOYOLU: 0,
        KUZEY_MARMARA_OTOYOLU: 0,
      },
    ],
  },
  {
       department: "İNSAN KAYNAKLARI VE EĞİTİM DAİRESİ BAŞKANLIĞI",
       units: [
      {
        id: 9448,
        department: "İNSAN KAYNAKLARI VE EĞİTİM DAİRESİ BAŞKANLIĞI",
        unit: "HAYAT BOYU ÖĞRENME ŞUBE MÜDÜRLÜĞÜ",
        total_count: 1,
        amount: 314,
        total: 10.24,
        ANKARA_NİĞDE_OTOYOLU: 0,
        AVRASYA_TÜNELİ: 0,
        GEBZE_ORHANGAZİ_İZMİR_OTOYOLU: 0,
        İSTANBUL_DENİZ_OTOBÜSLERİ_İDO: 0,
        KARAYOLLARI_GENEL_MÜDÜRLÜĞÜ: 10.24,
        KUZEY_ÇEVRE_OTOYOLU: 0,
        KUZEY_EGE_OTOYOLU: 0,
        KUZEY_MARMARA_OTOYOLU: 0,
      },
    ],
  },
  {
    department: "SOSYAL HİZMETLER DAİRESİ BAŞKANLIĞI",

    units: [
      {
        id: 11145,
        department: "SOSYAL HİZMETLER DAİRESİ BAŞKANLIĞI",
        unit: "ENGELLİLER ŞUBE MÜDÜRLÜĞÜ",
        total_count: 1,
        amount: 314,
        total: 10.23,
        ANKARA_NİĞDE_OTOYOLU: 0,
        AVRASYA_TÜNELİ: 0,
        GEBZE_ORHANGAZİ_İZMİR_OTOYOLU: 0,
        İSTANBUL_DENİZ_OTOBÜSLERİ_İDO: 0,
        KARAYOLLARI_GENEL_MÜDÜRLÜĞÜ: 10.23,
        KUZEY_ÇEVRE_OTOYOLU: 0,
        KUZEY_EGE_OTOYOLU: 0,
        KUZEY_MARMARA_OTOYOLU: 0,
      },
    ],
  },
  {
    department: "GENEL SEKRETER YARDIMCISI MAHİR BEY",

    units: [
      
      {
        id: 11008,
        department: "GENEL SEKRETER YARDIMCISI MAHİR BEY",
        unit: "GENEL SEKRETER YARDIMCISI MAHİR BEY",
        total_count: 1,
        amount: 314,
        total: 8.25,
        ANKARA_NİĞDE_OTOYOLU: 0,
        AVRASYA_TÜNELİ: 0,
        GEBZE_ORHANGAZİ_İZMİR_OTOYOLU: 0,
        İSTANBUL_DENİZ_OTOBÜSLERİ_İDO: 0,
        KARAYOLLARI_GENEL_MÜDÜRLÜĞÜ: 8.25,
        KUZEY_ÇEVRE_OTOYOLU: 0,
        KUZEY_EGE_OTOYOLU: 0,
        KUZEY_MARMARA_OTOYOLU: 0,
      },
    ],
  },
  {
    department: "DESTEK HİZMETLERİ DAİRESİ BAŞKANLIĞI",

    units: [
      {
        id: 9847,
        department: "DESTEK HİZMETLERİ DAİRESİ BAŞKANLIĞI",
        unit: "ADLİYE",
        total_count: 932,
        amount: 1149738,
        total: 11.23,
        ANKARA_NİĞDE_OTOYOLU: 0,
        AVRASYA_TÜNELİ: 0,
        GEBZE_ORHANGAZİ_İZMİR_OTOYOLU: 0,
        İSTANBUL_DENİZ_OTOBÜSLERİ_İDO: 0,
        KARAYOLLARI_GENEL_MÜDÜRLÜĞÜ: 11.23,
        KUZEY_ÇEVRE_OTOYOLU: 0,
        KUZEY_EGE_OTOYOLU: 0,
        KUZEY_MARMARA_OTOYOLU: 0,
      },
      {
        id: 10605,
        department: "DESTEK HİZMETLERİ DAİRESİ BAŞKANLIĞI",
        unit: "ANADOLU ADLİYESİ",
        total_count: 8,
        amount: 9314,
        total: 10.43,
        ANKARA_NİĞDE_OTOYOLU: 0,
        AVRASYA_TÜNELİ: 0,
        GEBZE_ORHANGAZİ_İZMİR_OTOYOLU: 0,
        İSTANBUL_DENİZ_OTOBÜSLERİ_İDO: 0,
        KARAYOLLARI_GENEL_MÜDÜRLÜĞÜ: 10.43,
        KUZEY_ÇEVRE_OTOYOLU: 0,
        KUZEY_EGE_OTOYOLU: 0,
        KUZEY_MARMARA_OTOYOLU: 0,
      },
      {
        id: 10752,
        department: "DESTEK HİZMETLERİ DAİRESİ BAŞKANLIĞI",
        unit: "BEYKOZ ADLİYESİ",
        total_count: 136,
        amount: 161852,
        total: 10.53,
        ANKARA_NİĞDE_OTOYOLU: 0,
        AVRASYA_TÜNELİ: 0,
        GEBZE_ORHANGAZİ_İZMİR_OTOYOLU: 0,
        İSTANBUL_DENİZ_OTOBÜSLERİ_İDO: 0,
        KARAYOLLARI_GENEL_MÜDÜRLÜĞÜ: 10.53,
        KUZEY_ÇEVRE_OTOYOLU: 0,
        KUZEY_EGE_OTOYOLU: 0,
        KUZEY_MARMARA_OTOYOLU: 0,
      },
      {
        id: 11774,
        department: "DESTEK HİZMETLERİ DAİRESİ BAŞKANLIĞI",
        unit: "BÜYÜKÇEKMECE ADLİYESİ",
        total_count: 2,
        amount: 2678,
        total: 12,
        ANKARA_NİĞDE_OTOYOLU: 0,
        AVRASYA_TÜNELİ: 0,
        GEBZE_ORHANGAZİ_İZMİR_OTOYOLU: 0,
        İSTANBUL_DENİZ_OTOBÜSLERİ_İDO: 0,
        KARAYOLLARI_GENEL_MÜDÜRLÜĞÜ: 12,
        KUZEY_ÇEVRE_OTOYOLU: 0,
        KUZEY_EGE_OTOYOLU: 0,
        KUZEY_MARMARA_OTOYOLU: 0,
      },
      {
        id: 11377,
        department: "DESTEK HİZMETLERİ DAİRESİ BAŞKANLIĞI",
        unit: "DESTEK HİZMETLERİ ŞUBE MÜDÜRLÜĞÜ",
        total_count: 18,
        amount: 25495,
        total: 11.23,
        ANKARA_NİĞDE_OTOYOLU: 0,
        AVRASYA_TÜNELİ: 0,
        GEBZE_ORHANGAZİ_İZMİR_OTOYOLU: 0,
        İSTANBUL_DENİZ_OTOBÜSLERİ_İDO: 0,
        KARAYOLLARI_GENEL_MÜDÜRLÜĞÜ: 11.23,
        KUZEY_ÇEVRE_OTOYOLU: 0,
        KUZEY_EGE_OTOYOLU: 0,
        KUZEY_MARMARA_OTOYOLU: 0,
      },
      {
        id: 13212,
        department: "DESTEK HİZMETLERİ DAİRESİ BAŞKANLIĞI",
        unit: "İŞLETMELER ŞUBE MÜDÜRLÜĞÜ",
        total_count: 2,
        amount: 288,
        total: 12.23,
        ANKARA_NİĞDE_OTOYOLU: 0,
        AVRASYA_TÜNELİ: 0,
        GEBZE_ORHANGAZİ_İZMİR_OTOYOLU: 0,
        İSTANBUL_DENİZ_OTOBÜSLERİ_İDO: 0,
        KARAYOLLARI_GENEL_MÜDÜRLÜĞÜ: 12.23,
        KUZEY_ÇEVRE_OTOYOLU: 0,
        KUZEY_EGE_OTOYOLU: 0,
        KUZEY_MARMARA_OTOYOLU: 0,
      },
      {
        id: 12827,
        department: "İTFAİYE DAİRESİ BAŞKANLIĞI",
        unit: "ANADOLU YAKASI İTFAİYE ŞUBE MÜDÜRLÜĞÜ",
        total_count: 1,
        amount: 1339,
        total: 15.23,
        ANKARA_NİĞDE_OTOYOLU: 0,
        AVRASYA_TÜNELİ: 0,
        GEBZE_ORHANGAZİ_İZMİR_OTOYOLU: 0,
        İSTANBUL_DENİZ_OTOBÜSLERİ_İDO: 0,
        KARAYOLLARI_GENEL_MÜDÜRLÜĞÜ: 15.23,
        KUZEY_ÇEVRE_OTOYOLU: 0,
        KUZEY_EGE_OTOYOLU: 0,
        KUZEY_MARMARA_OTOYOLU: 0,
      },
      {
        id: 9821,
        department: "İTFAİYE DAİRESİ BAŞKANLIĞI",
        unit: "AVRUPA YAKASI İTFAİYE ŞUBE MÜDÜRLÜĞÜ",
        total_count: 5,
        amount: 2189,
        total: 18.23,
        ANKARA_NİĞDE_OTOYOLU: 0,
        AVRASYA_TÜNELİ: 0,
        GEBZE_ORHANGAZİ_İZMİR_OTOYOLU: 0,
        İSTANBUL_DENİZ_OTOBÜSLERİ_İDO: 0,
        KARAYOLLARI_GENEL_MÜDÜRLÜĞÜ: 18.23,
        KUZEY_ÇEVRE_OTOYOLU: 0,
        KUZEY_EGE_OTOYOLU: 0,
        KUZEY_MARMARA_OTOYOLU: 0,
      },
      {
        id: 11868,
        department: "TARIMSAL HİZMETLER DAİRESİ BAŞKANLIĞI ",
        unit: "HAL ŞUBE MÜDÜRLÜĞÜ",
        total_count: 1,
        amount: 1339,
        total: 5.23,
        ANKARA_NİĞDE_OTOYOLU: 0,
        AVRASYA_TÜNELİ: 0,
        GEBZE_ORHANGAZİ_İZMİR_OTOYOLU: 0,
        İSTANBUL_DENİZ_OTOBÜSLERİ_İDO: 0,
        KARAYOLLARI_GENEL_MÜDÜRLÜĞÜ: 15.23,
        KUZEY_ÇEVRE_OTOYOLU: 0,
        KUZEY_EGE_OTOYOLU: 0,
        KUZEY_MARMARA_OTOYOLU: 0,
      },
    ],
  },
];
