export const  SET_TOLL_DATA = 'SET_TOLL_DATA';
export const  SET_TOLL_ERROR = 'SET_TOLL_ERROR';
export const  CLEAR_TOLL_ERROR = 'CLEAR_TOLL_ERROR';
export const LOADING_TOLL_DATA = 'LOADING_TOLL_DATA';
export const  SET_TOLL_MESSAGE = 'SET_TOLL_MESSAGE';
export const  CLEAR_TOLL_MESSAGE = 'CLEAR_TOLL_MESSAGE';